### ISSUE TITLE
Supporting Multiple Users From Hadoop

### ISSUE THREAD

**Issue by bucklerjj** [quantcast/qfs#16]
I am wondering if there are plans to support multiple users from Hadoop.  Currently, it seems that a MapReduce task that opens a QFS file system will assume the uid and gid of the task JVM.  

In our case that means all QFS file interactions were occurring as the mapred user.  Since we are integrating QFS into an existing cluster that has multiple users owning files in HDFS, making all files accessible (and owned) by mapred was not acceptable.

Our approach was to modify the initialize() method of the QuantcastFileSystem class to check for some Hadoop side information to try to determine the Hadoop user instead of just the user running the JVM.  We first created a check for three config variables for user ID, group ID, and alternate group IDS (qfs.uid, qfs.gid, qfs.gids).  If these were found we called a new QFSImpl constructor with the values.  If the config variables were not found, we pull user and groups from a Hadoop UserGroupInformation class and pass those down to a second new QFSImpl constructor.  In both cases, we make calls down into the C++ layer to set the effective user and group.

The reason we did the two different pathways was that some of our users do not exist as local accounts on all of our Hadoop nodes.  Therefore looking up the hadoop user and group locally to get uid and gid would fail.  Therefore explicitly setting the IDs in the Hadoop config variables gave a way for these users to create and read their files on every node.

What other ways are people handling multiple users and file owners?

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-16
