### ISSUE TITLE
Where is the function 'Evicting Chunks'  implemented in code？

### ISSUE THREAD

**Issue by xiaoyangzhang1993** [quantcast/qfs#163]
Hi ,I have a question.

Where is the function 'Evicting Chunks'  implemented in code？I did not find it.
The function 'Evicting Chunks' is in the chapter ’2.3.4 Evicting Chunks‘ of paper "The Quantcast File System" 

Thanks.

**Comment by mckurt** [comment]
Hi, 

You can find the related functions in src/cc/chunk/ChunkManager.cc. For example, the following function schedules an evacuation operation on a chunkdir: https://github.com/quantcast/qfs/blob/master/src/cc/chunk/ChunkManager.cc#L6739

Evacuation of a chunkdir is triggered by creating a "evacuate" file under that chunkdir path. A chunkserver periodically checks the existence of the "evacuate" file, and if there is one, it triggers the evacuation action. Check out https://github.com/quantcast/qfs/wiki/Administrator's-Guide#evacuation to see how evacuation on a chunk directory is triggered.

Best,

Mehmet

**Comment by xiaoyangzhang1993** [comment]
Hi Mehmet,

Thanks for your reply! I have another question.

How does QFS handle a chunk server failure? Based on "_Eviction is a request to recreate a chunk server’s data elsewhere so that its machine can be safely taken down, for example for repairs or upgrades_" cited from ’2.3.4 Evicting Chunks‘ of paper "The Quantcast File System", I guess QFS triggers a single-failure repair using the evacuation operation. Is that right?

Thank you!

BTW, our goal is to evaluate the repair time for a chunk server failure in QFS.

Yours sincerely,
Xiaoyang

**Comment by mckurt** [comment]
Hello again,

Actually, evacuation is used for intended downtime such as repairs or upgrades as indicated in the paper. For chunkserver recovery, you're right. Once the metaserver discovers that a chunkserver has gone and probably will not come back, it recovers the chunks in the failed chunkserver either with RS recovery or replication in another chunkserver.

That's interesting. Are you guys planning to make a comparison with other filesystems? In any case, we'd be very interested in hearing back on your progress & results.

I also encourage you to sign up to QFS JIRA: https://quantcast.atlassian.net
You can post any questions/feature requests/bugs there as well.

Let me know if you have any further questions.

Best,

Mehmet

**Comment by YuchongHu** [comment]
Dear Mehmet,

Nice to meet you! I am with the same team of the xiaoyangzhang1993.

Thank you for your reply. It really helps! We will sign up to QFS JIRA soon.

Yes, we are trying to compare QFS with HDFS-RAID (hadoop 20) and implement more coding schemes (like LRC, RC etc.) apart from erasure coding.  We think the implementation of QFS is pretty neat.

And we have a further question:  could you tell us who (metaserver or the new chunk server) does the RS recovery when recovering the lost chunks? 

Thanks.

Yours sincerely,
Yuchong

**Comment by mckurt** [comment]
Hi @YuchongHu,

If there is a failed/disconnected chunkserver, metaserver picks a chunkserver among remaining ones and the chosen chunkserver performs the RS recovery.

For a more detailed discussion, you can check the following group post: https://groups.google.com/forum/#!searchin/qfs-devel/recovery/qfs-devel/AXbgqXkMY7s/ZwLf7J2SeRoJ

Mehmet

**Comment by YuchongHu** [comment]
Dear Mehmet,

We have got a lot of useful information from you :)
Really appreciate your help!

Yours sincerely,
Yuchong

**Comment by mckurt** [comment]
Sure. Looking forward to seeing your results.
Mehmet
