### ISSUE TITLE
Error handling suggests cluster key mismatch when actually md5sum mismatch; fix message

### ISSUE THREAD

**Issue by autocracy** [quantcast/qfs#168]
The status EBADCLUSTERKEY can also indicate an md5 mismatch as used in

https://github.com/quantcast/qfs/blob/9f6b4887b6fe60ee06e39bacf7fa2e14436bf5b0/src/cc/chunk/MetaServerSM.cc#L701

Request a more specific error code or a human readable error message that notes other possible mismatch conditions represented by this error code.

**Comment by mckurt** [comment]
Hi @autocracy,

Thanks for reaching out :) This issue is being tracked in https://quantcast.atlassian.net/browse/QFS-187. We'll get to it soon.

Thanks,

**Comment by mckurt** [comment]
A fix is in place.
