### ISSUE TITLE
No tarball target for make

### ISSUE THREAD

**Issue by michaelkamprath** [quantcast/qfs#172]
On the [Migration Guide](https://github.com/quantcast/qfs/wiki/Migration-Guide) wiki page, it indicates that one can make a tarsal based off a custom build by using make tarball. However, there is no target for tarball in make file.

```
~/qfs$ make tarball
make: *** No rule to make target `tarball'.  Stop.
```

**Comment by mckurt** [comment]
Hi @michaelkamprath, are you sure you're in the right directory? https://github.com/quantcast/qfs/blob/master/Makefile#L49

```
US01307-ml:qfs mcankurt$ make tarball
export BUILD_TYPE=debug
mkdir -p build/debug
cd build/debug && cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo ../..
-- The C compiler identification is AppleClang 7.0.0.7000176
```

**Comment by michaelkamprath** [comment]
@mckurt I see my mistake. I used cmake to make the build, and that overwrote the Makefile.
