### ISSUE TITLE
Problem building on Ubuntu 14.04

### ISSUE THREAD

**Issue by mrosen** [quantcast/qfs#179]
I'm following the guidance in the wiki but the build fails after configuration ("gf-complete/configure: not found").  Any thoughts on what's wrong?  Console follows

vagrant@vagrant-ubuntu-trusty-64:/odm_app_copy/odm_app/qfs$ make
export BUILD_TYPE=debug
mkdir -p build/debug
cd build/debug && cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo ../..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   regex
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers:
-- Found kerberos 5 libs:      /usr/lib/x86_64-linux-gnu/libkrb5.so;/usr/lib/x86_64-linux-gnu/libk5crypto.so;/usr/lib/x86_64-linux-gnu/libcom_err.so
-- Detected kerberos 5 flavor: MIT
-- Build binaries with statically linked QFS libraries
-- Building qfs_fuse
-- fuse libs:         /usr/lib/x86_64-linux-gnu/libfuse.so
-- fuse include dirs: /usr/include
-- fuse definitions:  -D_FILE_OFFSET_BITS=64
-- System name: Linux
-- System processor: x86_64
-- qcrs: enabling ssse3
-- qcrs: enabling -O3 flag
-- Configuring done
-- Generating done
-- Build files have been written to: /odm_app_copy/odm_app/qfs/build/debug
cd build/debug && make  install
make[1]: Entering directory `/odm_app_copy/odm_app/qfs/build/debug'
make[2]: Entering directory `/odm_app_copy/odm_app/qfs/build/debug'
make[2]: Warning: File `CMakeFiles/Makefile2' has modification time 6.2 s in the future
make[3]: Entering directory `/odm_app_copy/odm_app/qfs/build/debug'
make[3]: Warning: File `CMakeFiles/Gf_complete_proj.dir/progress.make' has modification time 5.4 s in the future
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Leaving directory `/odm_app_copy/odm_app/qfs/build/debug'
make[3]: Entering directory `/odm_app_copy/odm_app/qfs/build/debug'
make[3]: Warning: File `CMakeFiles/Gf_complete_proj.dir/progress.make' has modification time 5.3 s in the future
[  0%] Performing configure step for 'Gf_complete_proj'
/bin/sh: 1: /odm_app_copy/odm_app/qfs/ext/gf-complete/configure: not found
make[3]: *** [Gf_complete_proj-prefix/src/Gf_complete_proj-stamp/Gf_complete_proj-configure] Error 127
make[3]: Leaving directory `/odm_app_copy/odm_app/qfs/build/debug'
make[2]: *** [CMakeFiles/Gf_complete_proj.dir/all] Error 2
make[2]: Leaving directory `/odm_app_copy/odm_app/qfs/build/debug'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/odm_app_copy/odm_app/qfs/build/debug'
make: *** [build] Error 2
vagrant@vagrant-ubuntu-trusty-64:/odm_app_copy/odm_app/qfs$

**Comment by kstinsonqc** [comment]
A proper git clone of qfs should have a ext/gf-complete/configure file and building the project should not change this file.

Please check to see if this file exists in your copy of qfs. If not, try recloning the project and trying again.

**Comment by mckurt** [comment]
Please feel free to reopen the issue if it is not resolved yet.
