### ISSUE TITLE
launch chunkserver and see error-2 in log

### ISSUE THREAD

**Issue by dean-chen** [quantcast/qfs#190]
My first time to launch chunkserver, the LOG severity is INFO, but see error -2 code in detail message, do not know what happened.

> $ tail -f nohup.out 
> 10-14-2016 00:04:27.437 INFO - (DiskIo.cc:2711)  0x12d5920 0x1b04b60fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.437 INFO - (DiskIo.cc:2711)  0x14a6f60 0x1b04e60fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.437 INFO - (MetaServerSM.cc:374) setting chunk server ip to: 10.140.110.112
> 10-14-2016 00:04:27.437 INFO - (MetaServerSM.cc:463) Sending hello to meta server: meta-hello: seq: 3024384142586849421 mylocation: 10.140.110.112 22000 cluster-key: dean-qfs md5sum: 886bc5b28184cab6ceca4b2e923919d0 rackId: -1 space: 47978842619904 used: 0 chunks: 0 not-stable: 0 append: 0 fsid: -1 metafsid: -1 delete flag: 0
> 10-14-2016 00:04:27.437 INFO - (DiskIo.cc:2711)  0x158fc80 0x1b05db0fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.437 INFO - (DiskIo.cc:2711)  0x16787a0 0x1b05f30fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.438 INFO - (DiskIo.cc:2711)  0x17612c0 0x1b060b0fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.438 INFO - (DiskIo.cc:2711)  0x1849de0 0x1b06230fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.438 INFO - (DiskIo.cc:2711)  0x1932b00 0x1b063b0fs space available (0 0) error: -2 get fs available No such file or directory 2
> 10-14-2016 00:04:27.438 INFO - (DiskIo.cc:2711)  0x1a1b620 0x1b06530fs space available (0 0) error: -2 get fs available No such file or directory 2
> 

the chunk dirs are 

> chunkServer.chunkDir = /data/slot0 /data/slot1 /data/slot2 /data/slot3 /data/slot4 /data/slot5 /data/slot6 /data/slot7 /data/slot8 /data/slot9 /data/slota /data/slotb

**Comment by mckurt** [comment]
Hello, 

Chunkservers periodically check if any of the chunk dirs contains a file called "evacuate". If this file exists, chunkserver starts to evacuate the chunks in the corresponding chunk dir. 

This INFO message basically means that there is no "evacuate" file under a chunk dir, and it can be discarded, i.e. chunkserver will continue to serve normally. Although the message level is INFO (but not ERROR), I agree that the message is a little misleading and we will fix it soon. 

Let me know if you have any other question,
