### ISSUE TITLE
qfshibernate breaks metaserver

### ISSUE THREAD

**Issue by MrStupnikov** [quantcast/qfs#224]
qfshibernate breaks metaserver
=========================

**Steps to reproduce**

1. Setup simplest QFS cluster (I have used different configurations including standalone metaserver and chunk servers, VR, and sample_setup.py).
2. Try to hibernate some chunk server. Use the following command [template](https://github.com/quantcast/qfs/wiki/Administrator%27s-Guide#qfshibernate)

- **Expected result:** chunk server is hibernated and restored later
- **Actual result:** metaserver process crashes without any log messages generated (DEBUG log level is used), client returns the following [error](https://pastebin.com/vFm3qyt2)

**Comment by mikeov** [comment]
Thank for your report.
The following commit is intended to address the problem:
https://github.com/quantcast/qfs/commit/67f0ee6c24581e3522ab02b15510268a92bb4252
