### ISSUE TITLE
Add directory/file paths to log messages

### ISSUE THREAD

**Issue by chu11** [quantcast/qfs#31]
I was getting log messages like the following:

08-07-2013 13:41:17.249 INFO - (DiskIo.cc:XXXX) fs space available (0 0) error: -2 get fs available No such file or directory 2

I didn't know if these were issues or not, and without information about what directory was missing, I didn't know how to proceed.  After debugging, I eventually realized the missing file was the 'evacuate' file.  It'd be nice if it were just output from the start.

I wrote a patch to do this at the branch logdirectorypath at https://github.com/chu11/qfs.git

I now get a log message like this:

08-08-2013 14:34:07.160 INFO - (DiskIo.cc:2141) fs space available (0 0) error: -2 get fs available No such file or directory 2 /scratch/achu/evacuate

The patch I wrote is sort of a hack.  I think something better would be if the IoRetCode, CompletionCode, and my new PathError variable were put into some encapsulated "Error" class.  Decided such an effort wasn't a good idea until a discussion.

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-31
