### ISSUE TITLE
File size increased incredible when appending

### ISSUE THREAD

**Issue by jeffwji** [quantcast/qfs#32]
Recently, I did two tests to check the appending function of Kfs, one was from command line, the other one was from java API, but both failed. The tests I made are below:

Command line:
==============
1. Created a file.txt, which the content was "abcdefghi", the size shown was 11 bytes.

2. Created file1.txt which was copied from file.txt

3. In kfsshell, run command: "append file.txt file1.txt".

4. I got the message "append status:  offset: 402653184". And file.txt size changed to 0, file1.txt changed to 402653184!
file.txt        \<rs 1,6+3\>      rw-rw-r--       jeff    jeff    0       Aug 13 14:21
file1.txt       \<rs 1,6+3\>      rw-rw-r--       jeff    jeff    402653195       Aug 13 14:21

5. Executed "qfscat" command, I got the following error messages:
/qfs/tmp/file1.txt: Input/output error 5
08-13-2013 15:16:43.740 ERROR - (Reader.cc:1637) PW 0,52,3,file1.txt no such chunk -- hole: pos: 67108864 + 0 requested: 720896
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 1 bad: 0 round: 0
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1892) PW 0,52,3,file1.txt init recovery: req: 0,4194304 pos: 0 size: 720896 [0,720896)
08-13-2013 15:16:43.740 ERROR - (Reader.cc:1637) PW 0,52,3,file1.txt no such chunk -- hole: pos: 134217728 + 0 requested: 720896
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 2 bad: 1 round: 0
08-13-2013 15:16:43.740 ERROR - (Reader.cc:1637) PW 0,52,3,file1.txt no such chunk -- hole: pos: 201326592 + 0 requested: 720896
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 3 bad: 2 round: 0
08-13-2013 15:16:43.740 ERROR - (Reader.cc:1637) PW 0,52,3,file1.txt no such chunk -- hole: pos: 268435456 + 0 requested: 655360
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 4 bad: 3 round: 0
08-13-2013 15:16:43.740 ERROR - (Reader.cc:1637) PW 0,52,3,file1.txt no such chunk -- hole: pos: 335544320 + 0 requested: 655360
08-13-2013 15:16:43.740 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 5 bad: 4 round: 0
08-13-2013 15:16:43.770 ERROR - (Reader.cc:1294) PW 0,52,3,file1.txt short read detected: chunk: 345 version: 1 server: 127.0.0.1 21002 pos: 0 requested: 720896 returned: 11 size: 11
08-13-2013 15:16:43.770 WARN - (Reader.cc:2196) PW 0,52,3,file1.txt invalid chunk: 345 version: 1 status: -1007 msg: short read detected
08-13-2013 15:16:43.770 ERROR - (Reader.cc:1468) PW 0,52,3,file1.txt operation failure, seq: 580520357837216307 status: -1007 msg: short read detected op: read: chunkid: 345 version: 1 offset: 0 numBytes: 720896 iotm: 0.013235 skip-disk-chksum current chunk server: 127.0.0.1 21002 chunkserver: all data sent
Request:
READ
Cseq: 580520357837216307
Version: KFS/1.0
Client-Protocol-Version: 114
UserId: 500
GroupId: 500
User: jeff
Max-wait-ms: 30000
Chunk-handle: 345
Chunk-version: 1
Offset: 0
Num-bytes: 720896
Skip-Disk-Chksum: 1
08-13-2013 15:16:43.770 INFO - (Reader.cc:1583) PW 0,52,3,file1.txt scheduling retry: 0 of 30 in 0 sec. op: read: chunkid: 345 version: 1 offset: 0 numBytes: 720896 iotm: 0.013235 skip-disk-chksum
08-13-2013 15:16:43.778 ERROR - (Reader.cc:1294) PW 0,52,3,file1.txt short read detected: chunk: 345 version: 1 server: 127.0.0.1 21001 pos: 0 requested: 720896 returned: 11 size: 11
08-13-2013 15:16:43.778 WARN - (Reader.cc:2196) PW 0,52,3,file1.txt invalid chunk: 345 version: 1 status: -1007 msg: short read detected
08-13-2013 15:16:43.778 INFO - (RSStriper.cc:1806) PW 0,52,3,file1.txt read failure: req: 0,4194304 status: -1007 stripe: 0 bad: 5 round: 0
08-13-2013 15:16:43.778 INFO - (RSStriper.cc:1976) PW 0,52,3,file1.txt read recovery failed: req: 0,4194304 status: -5 round: 0 bad stripes: 6 turning on read retries
08-13-2013 15:16:43.778 ERROR - (RSStriper.cc:2016) PW 0,52,3,file1.txt read recovery failed: req: 0,4194304 status: 0 bad stripes: 6 invalid chunks: 6 pending: 0

6. cpfromqfs failed with the same message, but with "-S" argument successfully.

API:
================
1. Created file.txt with "kfsAccess.kfs_create(String fileName)"

2. Appended it with "kfsAccess.kfs_append(String fileName)", it returned:
08-13-2013 14:29:39.571 INFO - (WriteAppender.cc:1436) PW 0,49,2,file.txt scheduling retry: 1 of 30 in 5 sec. op: allocate: fid: 49 offset: 0
08-13-2013 14:29:44.576 ERROR - (WriteAppender.cc:1333) PW 0,49,2,file.txt operation failure, seq: 1968023330218062915 status: -22 msg: append is not supported with striped files op: allocate: fid: 49 offset: 0 current chunk server:  -1 chunkserver: no data sent
Request:
ALLOCATE
Cseq: 1968023330218062914
Version: KFS/1.0
Client-Protocol-Version: 114
UserId: 500
GroupId: 500
User: jeff
Max-wait-ms: 30000
Client-host: centos.localdomain
Pathname: /qfs/tmp/file.txt
File-handle: 49
Chunk-offset: 0
Chunk-append: 1
Space-reserve: 11
Max-appenders: 64

3. Created file.txt with "STRIPED_FILE_TYPE_NONE:
 kfsAccess.kfs_create_ex(fileName, 
				kfsAccess.DEFAULT_APPEND_REPLICATION, 
				false, -1, -1, 
				kfsAccess.DEFAULT_NUM_STRIPES,
				kfsAccess.DEFAULT_NUM_RECOVERY_STRIPES, 
				kfsAccess.DEFAULT_STRIPE_SIZE, 
				1,              // STRIPED_FILE_TYPE_NONE
				false,
				0666);
Now I have a file the strip type is 'r', which is different to the one created from command line('rs').
file.txt        \<r 2\>   rw-rw-r--       jeff    jeff    11      Aug 13 14:33

4. Tried the 2nd step again, it was success, but the size changed to 134217728
file.txt        \<r 2\>   rw-rw-r--       jeff    jeff    134217728       Aug 13 14:34

5. Cat the content, it returned error:
08-13-2013 14:38:09.537 ERROR - (Reader.cc:1294) PW 0,50,3,file.txt short read detected: chunk: 336 version: 1 server: 127.0.0.1 21002 pos: 1048576 requested: 1048576 returned: 0 size: 11
08-13-2013 14:38:09.537 WARN - (Reader.cc:2196) PW 0,50,3,file.txt invalid chunk: 336 version: 1 status: -1007 msg: short read detected
08-13-2013 14:38:09.537 ERROR - (Reader.cc:1468) PW 0,50,3,file.txt operation failure, seq: 0 status: -1007 msg: short read detected op: read: chunkid: 336 version: 1 offset: 1048576 numBytes: 1048576 iotm: 0 skip-disk-chksum current chunk server: 127.0.0.1 21002 chunkserver: all data sent
Request:
READ
Cseq: 0
Version: KFS/1.0
Client-Protocol-Version: 114
UserId: 500
GroupId: 500
User: jeff
Chunk-handle: 336
Chunk-version: 1
Offset: 1048576
Num-bytes: 1048576
Skip-Disk-Chksum: 1

6. cpfromqfs failed without "-S" argument.

I have 3 questions:
-------------------
1. Why the file create with 'rs' mode(striped) from command line can be appended, but API failed? when a file has be created, normally we cannot guarantee it will not been appended in the future, so if 'rs' mode works for appending (like shell command does), why we have to create it with 'r' mode?

2. why the size shows normal before it has been appended but incorrect after?
I found some one explained it's because of the strip size increased. But how I can compute the exactly quota consumed? Is there any way to shrink it to the right number?

3. howevery the cpformqfs command has '-S' argument to skip holes, and return the useful content, how about qfscat and API?

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-32
