### ISSUE TITLE
throughout is only 50MB

### ISSUE THREAD

**Issue by zihuangning** [quantcast/qfs#33]
netspeed:1000Mb
replication:3

sample code:

 int localfid = open("tests/testlog500m", O_RDONLY);

do{
     |   readlocallen = read(localfid, dataBuf, writeSizeBytes);
     |   strm.avail_in = readlocallen;
     |   if(readlocallen > 0) {
     |   |   gettimeofday(&s1, NULL);
     |   |   res = gKfsClient->Write(fd, dataBuf, writeSizeBytes);
     |   |   gettimeofday(&s2, NULL);
     |   |   timediff = (s2.tv_sec * 1000000.0 + s2.tv_usec) - (s1.tv_sec * 1000000.0 + s1.tv_usec);
     |   |  timeall += timediff;
     |   }
     |   nwrote += writeSizeBytes;
     } while (readlocallen > 0);
     close(localfid);    
cout << "write of " << nwrote / (1024 * 1024) / timeall * 1000000<< " (MB/s) is done" << endl;

why?

it is my first time to use github,sorry.

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-33
