### ISSUE TITLE
qfsc unit tests failing on ubuntu precise32

### ISSUE THREAD

**Issue by stevvooe** [quantcast/qfs#39]
Running `make test-release`, we get the following failure:

```
fail	test_qfs_get_data_locations
** expect count == expected_length: unexpected number of chunk locations: 2 != 4
fail
23 tests
```

Host information:

```
$ uname -a
Linux precise32 3.2.0-23-generic-pae #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC 2012 i686 i686 i386 GNU/Linux
```

The same test does not fail when using the "example setup". It's possible this test relies on having two chunkservers in the test setup.

I'm running a `git bisect` to track down the change that caused this test to fail on ubuntu.

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-39
