### ISSUE TITLE
Qfs cannot build with gcc-4.7

### ISSUE THREAD

**Issue by rchatsiri** [quantcast/qfs#42]
Qfs built source code with command line 
```make BOOST_INCLUDEDIR=~/boost_1_55_0/```
Cmake run by use gcc and g++ version 4.7. It's through error as below.

Scanning dependencies of target kfsMeta
[ 20%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/AuditLog.o
[ 20%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/Checkpoint.o
[ 21%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/ChunkServer.o
[ 21%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/ChildProcessTracker.o
[ 22%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/ClientSM.o
[ 22%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/DiskEntry.o
[ 23%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/kfsops.o
[ 23%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/kfstree.o
[ 24%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/LayoutManager.o
[ 24%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/Logger.o
[ 25%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/meta.o
[ 25%] Building CXX object src/cc/meta/CMakeFiles/kfsMeta.dir/MetaRequest.o
/home/rch/workspacecpp/qfs/src/cc/meta/MetaRequest.cc: In member function ‘virtual void KFS::MetaFsck::handle()’:
/home/rch/workspacecpp/qfs/src/cc/meta/MetaRequest.cc:2698:40: warning: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result [-Wunused-result]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make[3]: *** [src/cc/meta/CMakeFiles/kfsMeta.dir/MetaRequest.o] Error 4
make[2]: *** [src/cc/meta/CMakeFiles/kfsMeta.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release] Error 2

Results are compile from gcc version 4.8 had error same above. I'm not sure an error born from the compiler. Do you have any idea from build source code there?

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-42
