### ISSUE TITLE
POSIX compatibility -- please document differences.

### ISSUE THREAD

**Issue by onlyjob** [quantcast/qfs#48]
I couldn't find any information regarding POSIX compatibility in Wiki. If Quantcast FS do follow POSIX standard then please document differences (what's not implemented, etc.). Thanks.

**Comment by mikeov** [comment]
For now HDFS POSIX differences semantics might be used as rough guideline.

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-48
