### ISSUE TITLE
build with system libjerasure-dev

### ISSUE THREAD

**Issue by onlyjob** [quantcast/qfs#49]
Please support building with system `libjerasure-dev` as alternative to statically linked bundled library in `ext/`. Thanks.

**Comment by mikeov** [comment]
Why this is required?

**Comment by onlyjob** [comment]
For best practice and for proper compartmentalisation.
Bundled statically linked libraries is a security nightmare.
See https://wiki.debian.org/StaticLinking

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-49
