### ISSUE TITLE
read-only FS?

### ISSUE THREAD

**Issue by onlyjob** [quantcast/qfs#50]
I'm trying my first QFS cluster with 2 chunk servers (2 chunkdirs each). For some reason FUSE client mounts file system only in `ro` mode. I can create directory on QFS using `qfsshell` but command
~~~~
cat /etc/qfs/MetaServer.prp |  qfsput -s localhost -p 20000 -f MetaServer.prp
~~~~
create empty file:
~~~~
Wrote 0 to MetaServer.prp
~~~~
I don't see any errors in web UI... What could be the problem?

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-50
