### ISSUE TITLE
setting replication level

### ISSUE THREAD

**Issue by onlyjob** [quantcast/qfs#53]
Please document how to set replication level (with examples).

Command `qfs -setrep 2 /mnt/qfs/myfile` returns 
~~~~
file:///mnt/qfs/myfile: Invalid argument 22
~~~~
and leaves me confused without a clue about what am I doing wrong...

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-53
