### ISSUE TITLE
Filesystem Atomicity

### ISSUE THREAD

**Issue by schmitmd** [quantcast/qfs#55]
Qfs doesn't seem to provide filesystem atomicity.

If I'm in qfsshell in my qfs root directory like so (window #1):

qfsshell -s 10.10.0.50 -p 50000

QfsShell>ls -lha
testfile    <r 3>   rw-r--r--       ubuntu        ubuntu          1.2G  Feb 12 10:41

QfsShell>cp testfile foo

And in window #2:

QfsShell>cp foo bar

Window #2's cp command will complete first, cutting off the rest of the file.

A little later, Window #1's cp command will complete.
testfile is the same as foo but foo is not the same as bar.
(file listing from qfs-fuse):

%>ls -lha qfs2
-rw-r--r-- 0 ubuntu ubuntu 1.3G Feb 12 10:41 testfile
-rw-r--r-- 0 root     root     1.3G Feb 13 14:59 foo
-rw-r--r-- 0 root     root     307M Feb 13 14:53 bar

**Comment by mikeov** [comment]
Concurrent write only supported with append, and to some extent with replicated files, and it is not supported wit RS / striped files.

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-55
