### ISSUE TITLE
qfs/common/StBuffer.h:StringBuffer& StringBufferT::Copy(...) may be wrong

### ISSUE THREAD

**Issue by rainbowsworld** [quantcast/qfs#58]
hello,qfs/common/StBuffer.h:278 line exists problems. memcpy runs wrong when src_addr < dst_addr && src_addr + len > dst_addr. Here should be : 
   if(inPtr <= mBuf && mBuf < inPtr + inLen)
            memmove(mBuf,inPtr,inLen)

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-58
