### ISSUE TITLE
error while building mstress

### ISSUE THREAD

**Issue by maismail** [quantcast/qfs#59]
when i was trying to run ./mstress_install.sh localhost 
i go this error, i'm not sure if  there is an order for things to do before running mstress_install or there is a missing library

Scanning dependencies of target mstress_client
[ 96%] Building CXX object benchmarks/mstress/CMakeFiles/mstress_client.dir/mstress_client.cc.o
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc: In function ‘int CreateDFSPaths(Client*, AutoCleanupKfsClient*)’:
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc:376:17: error: aggregate ‘std::ostringstream os’ has incomplete type and cannot be defined
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc: In function ‘int StatDFSPaths(Client*, AutoCleanupKfsClient*)’:
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc:406:17: error: aggregate ‘std::ostringstream os’ has incomplete type and cannot be defined
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc: In function ‘int ListDFSPaths(Client*, AutoCleanupKfsClient*)’:
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc:455:17: error: aggregate ‘std::ostringstream os’ has incomplete type and cannot be defined
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc: In function ‘int RemoveDFSPaths(Client*, AutoCleanupKfsClient*)’:
/home/maism/src/qfs/benchmarks/mstress/mstress_client.cc:500:17: error: aggregate ‘std::ostringstream os’ has incomplete type and cannot be defined
make[3]: *** [benchmarks/mstress/CMakeFiles/mstress_client.dir/mstress_client.cc.o] Error 1
make[2]: *** [benchmarks/mstress/CMakeFiles/mstress_client.dir/all] Error 2
make[1]: *** [benchmarks/mstress/CMakeFiles/mstress-tarball.dir/rule] Error 2
make: *** [mstress-tarball] Error 2

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-59
