### ISSUE TITLE
Dynamic IPs for chunkservers

### ISSUE THREAD

**Issue by teodor-pripoae** [quantcast/qfs#69]
Hi,

I'm trying to run a qfs cluster inside docker. I have 1 metaserver and 3 chunkservers and all data is stored in persistent volumes on the docker host. After I restart the cluster, the master restores the data but cannot find the chunkservers becouse docker assigned a different IP to them.

Example
- docker run metaserver, ip: 172.17.0.2, can be accessed at 172.17.0.1:20000 (docker bridge)
- docker run chunk1, ip: 172.17.0.3, can be accessed at 172.17.0.1:22000 (docker bridge)
- docker run chunk2, ip: 172.17.0.4, can be accessed at 172.17.0.1:22001 (docker bridge)
- docker run chunk3, ip: 172.17.0.5, can be accessed at 172.17.0.1:22002 (docker bridge)

Here, all chunkservers have `chunkServer.metaServer.hostname` to `172.17.0.1` (docker bridge) so they are connecting successfully even if master have a different ip.

If I restart the docker containers, docker assigns them different ips and master thinks this chunkservers are down, even if they are running.

How can I bind a chunkserver to docker bridge ? If I try to set `chunkServer.clientIp=172.17.0.1` it fails becouse it cannot bind to that interface.

**Comment by teodor-pripoae** [comment]
It seems to be working, I was messing up with docker volumes, wrong path. 

The question is still valid, how can I set a fixed host/port for chunkserver ? When client connects from outside to metaserver, metaservers gives him the local chunk ip, not the public one. Is there a way to send public ip of chunkserver to metaserver when joining the cluster ?

**Comment by mikeov** [comment]
It should be possible to set chunk server ip address that qfs client uses by adding the following to the chunk server configuration file:

chunkServer.hostname = chunk.server.ip
