### ISSUE TITLE
Go library

### ISSUE THREAD

**Issue by teodor-pripoae** [quantcast/qfs#75]
Hi,

I'm planning to use QFS in a Go project. Is it any support for C API which I can then include as a native extension ? Calling C++ code from Go is not supported.

I can see protocol is very complex so a client rewrite in Go looks very hard.

Thank you,
Teodor

**Comment by fsareshwala** [comment]
Hi there,

We haven't released our go bindings but we are planning to do so soon. The protocol is based on HTTP and is plaintext, but yes, go bindings would be much easier to work with. I can't give an exact timeline of when the go bindings will be released, but there have been requests for it so we are going to get it out there for you guys!

**Comment by teodor-pripoae** [comment]
Hi,

Thank you, I can't wait to see the go bindings !

I was primary refering to the protocol for fetching/writing files for example. There needs to be connection to metaserver, fetch chunk locations, fetch each chunk and do reed solomon, backoff/retry, etc which are already implemented in the C++ client.

Will the Go library be native or it will use a C shim over the C++ API ?
